package entity;
// Generated Jul 9, 2020 4:09:42 PM by Hibernate Tools 4.3.1


import database.NewHibernateUtil;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;

/**
 * Diadiem generated by hbm2java
 */
public class Diadiem  implements java.io.Serializable {


     private Integer maDiaDiem;
     private String ten;
     private String diaChi;
     private int sucChua;
     private Set tochucs = new HashSet(0);

    public Diadiem() {
    }

	
    public Diadiem(String ten, String diaChi, int sucChua) {
        this.ten = ten;
        this.diaChi = diaChi;
        this.sucChua = sucChua;
    }
    public Diadiem(String ten, String diaChi, int sucChua, Set tochucs) {
       this.ten = ten;
       this.diaChi = diaChi;
       this.sucChua = sucChua;
       this.tochucs = tochucs;
    }
   
    public Integer getMaDiaDiem() {
        return this.maDiaDiem;
    }
    
    public void setMaDiaDiem(Integer maDiaDiem) {
        this.maDiaDiem = maDiaDiem;
    }
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }
    public String getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }
    public int getSucChua() {
        return this.sucChua;
    }
    
    public void setSucChua(int sucChua) {
        this.sucChua = sucChua;
    }
    public Set getTochucs() {
        return this.tochucs;
    }
    
    public void setTochucs(Set tochucs) {
        this.tochucs = tochucs;
    }

    public List<Diadiem> excuteQuery(String query){
        try{
            Session s = NewHibernateUtil.getSessionFactory().openSession();
            s.beginTransaction();
            Query q = s.createQuery(query);
            List<Diadiem> result = q.list();
            s.getTransaction().commit();
            return result;
        }catch(HibernateException e){
            System.out.println(e.getMessage());   
        }
        return null;
    }


}


