package entity;
// Generated Jul 9, 2020 4:09:42 PM by Hibernate Tools 4.3.1


import database.NewHibernateUtil;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;

/**
 * Hoinghi generated by hbm2java
 */
public class Hoinghi  implements java.io.Serializable {


     private Integer maHoiNghi;
     private String ten;
     private String moTaNgan;
     private String moTaChiTiet;
     private String anh;
     private Integer nguoiThamDu;
     private Set tochucs = new HashSet(0);

    public Hoinghi() {
    }

	
    public Hoinghi(String ten) {
        this.ten = ten;
    }
    public Hoinghi(String ten, String moTaNgan, String moTaChiTiet, String anh, Integer nguoiThamDu, Set tochucs) {
       this.ten = ten;
       this.moTaNgan = moTaNgan;
       this.moTaChiTiet = moTaChiTiet;
       this.anh = anh;
       this.nguoiThamDu = nguoiThamDu;
       this.tochucs = tochucs;
    }
   
    public Integer getMaHoiNghi() {
        return this.maHoiNghi;
    }
    
    public void setMaHoiNghi(Integer maHoiNghi) {
        this.maHoiNghi = maHoiNghi;
    }
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }
    public String getMoTaNgan() {
        return this.moTaNgan;
    }
    
    public void setMoTaNgan(String moTaNgan) {
        this.moTaNgan = moTaNgan;
    }
    public String getMoTaChiTiet() {
        return this.moTaChiTiet;
    }
    
    public void setMoTaChiTiet(String moTaChiTiet) {
        this.moTaChiTiet = moTaChiTiet;
    }
    public String getAnh() {
        return this.anh;
    }
    
    public void setAnh(String anh) {
        this.anh = anh;
    }
    public Integer getNguoiThamDu() {
        return this.nguoiThamDu;
    }
    
    public void setNguoiThamDu(Integer nguoiThamDu) {
        this.nguoiThamDu = nguoiThamDu;
    }
    public Set getTochucs() {
        return this.tochucs;
    }
    
    public void setTochucs(Set tochucs) {
        this.tochucs = tochucs;
    }

    public List<Hoinghi> excuteQuery(String query){
        try{
            Session s = NewHibernateUtil.getSessionFactory().openSession();
            s.beginTransaction();
            Query q = s.createQuery(query);
            List<Hoinghi> result = q.list();
            s.getTransaction().commit();
            return result;
        }catch(HibernateException e){
            System.out.println(e.getMessage());   
        }
        return null;
    }
    public int UpdateQuery(String query){
        Session s = NewHibernateUtil.getSessionFactory().openSession();
        s.beginTransaction();
        Query q = s.createQuery(query);
        int result = q.executeUpdate();
        return result;
    }
    public void Them(){
        Session s = NewHibernateUtil.getSessionFactory().openSession();   
        s.beginTransaction();
        s.persist(this);
        s.getTransaction().commit();
        s.close();
    }    
}


