package entity;
// Generated Jul 9, 2020 4:09:42 PM by Hibernate Tools 4.3.1


import database.NewHibernateUtil;
import java.util.Date;
import java.util.List;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;

/**
 * Lichsudangky generated by hbm2java
 */
public class Lichsudangky  implements java.io.Serializable {


     private LichsudangkyId id;
     private Date ngayDangKy;
     private String trangThai;

    public Lichsudangky() {
    }

	
    public Lichsudangky(LichsudangkyId id) {
        this.id = id;
    }
    public Lichsudangky(LichsudangkyId id, Date ngayDangKy, String trangThai) {
       this.id = id;
       this.ngayDangKy = ngayDangKy;
       this.trangThai = trangThai;
    }
   
    public LichsudangkyId getId() {
        return this.id;
    }
    
    public void setId(LichsudangkyId id) {
        this.id = id;
    }
    public Date getNgayDangKy() {
        return this.ngayDangKy;
    }
    
    public void setNgayDangKy(Date ngayDangKy) {
        this.ngayDangKy = ngayDangKy;
    }
    public String getTrangThai() {
        return this.trangThai;
    }
    
    public void setTrangThai(String trangThai) {
        this.trangThai = trangThai;
    }

    public void DangKiThamGia(){
        Session s = NewHibernateUtil.getSessionFactory().openSession();   
        s.beginTransaction();
        s.persist(this);
        s.getTransaction().commit();
        s.close();
    }
    public List<Lichsudangky> excuteQuery(String string) {
                try{
            Session s = NewHibernateUtil.getSessionFactory().openSession();
            s.beginTransaction();
            Query q = s.createQuery(string);
            List<Lichsudangky> result = q.list();
            s.getTransaction().commit();
            return result;
        }catch(HibernateException e){
            System.out.println(e.getMessage());   
        }
        return null;
    }

}


