package entity;
// Generated Jul 9, 2020 4:09:42 PM by Hibernate Tools 4.3.1

import database.NewHibernateUtil;
import java.util.List;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;




/**
 * LichsudangkyId generated by hbm2java
 */
public class LichsudangkyId  implements java.io.Serializable {


     private String userName;
     private int maHoiNghi;

    public LichsudangkyId() {
    }

    public LichsudangkyId(String userName, int maHoiNghi) {
       this.userName = userName;
       this.maHoiNghi = maHoiNghi;
    }
   
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public int getMaHoiNghi() {
        return this.maHoiNghi;
    }
    
    public void setMaHoiNghi(int maHoiNghi) {
        this.maHoiNghi = maHoiNghi;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LichsudangkyId) ) return false;
		 LichsudangkyId castOther = ( LichsudangkyId ) other; 
         
		 return ( (this.getUserName()==castOther.getUserName()) || ( this.getUserName()!=null && castOther.getUserName()!=null && this.getUserName().equals(castOther.getUserName()) ) )
 && (this.getMaHoiNghi()==castOther.getMaHoiNghi());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUserName() == null ? 0 : this.getUserName().hashCode() );
         result = 37 * result + this.getMaHoiNghi();
         return result;
   }   
    public List<LichsudangkyId> excuteQuery(String string) {
                try{
            Session s = NewHibernateUtil.getSessionFactory().openSession();
            s.beginTransaction();
            Query q = s.createQuery(string);
            List<LichsudangkyId> result = q.list();
            s.getTransaction().commit();
            return result;
        }catch(HibernateException e){
            System.out.println(e.getMessage());   
        }
        return null;
    }

}


