package entity;
// Generated Jul 9, 2020 4:09:42 PM by Hibernate Tools 4.3.1

import database.NewHibernateUtil;
import java.util.List;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;




/**
 * Nguoidung generated by hbm2java
 */
public class Nguoidung  implements java.io.Serializable {


     private String userName;
     private String tenUser;
     private String pass;
     private String email;
     private boolean tinhTrang;

    public Nguoidung() {
    }

    public Nguoidung(String userName, String tenUser, String pass, String email, boolean tinhTrang) {
       this.userName = userName;
       this.tenUser = tenUser;
       this.pass = pass;
       this.email = email;
       this.tinhTrang = tinhTrang;
    }
   
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getTenUser() {
        return this.tenUser;
    }
    
    public void setTenUser(String tenUser) {
        this.tenUser = tenUser;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public boolean getTinhTrang() {
        return this.tinhTrang;
    }
    
    public void setTinhTrang(boolean a) {
        this.tinhTrang = a;
    }
    public List<Nguoidung> excuteQuery(String string) {
                try{
            Session s = NewHibernateUtil.getSessionFactory().openSession();
            s.beginTransaction();
            Query q = s.createQuery(string);
            List<Nguoidung> result = q.list();
            s.getTransaction().commit();
            return result;
        }catch(HibernateException e){
            System.out.println(e.getMessage());   
        }
        return null;
    }
    
    public void ThemNguoiDung(){
        Session s = NewHibernateUtil.getSessionFactory().openSession();   
        s.beginTransaction();
        s.persist(this);
        s.getTransaction().commit();
        s.close();
    }

}


