package entity;
// Generated Jul 9, 2020 4:09:42 PM by Hibernate Tools 4.3.1

import database.NewHibernateUtil;
import java.util.List;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;




/**
 * Tochuc generated by hbm2java
 */
public class Tochuc  implements java.io.Serializable {


     private TochucId id;
     private Diadiem diadiem;
     private Hoinghi hoinghi;

    public Tochuc() {
    }

    public Tochuc(TochucId id, Diadiem diadiem, Hoinghi hoinghi) {
       this.id = id;
       this.diadiem = diadiem;
       this.hoinghi = hoinghi;
    }
   
    public TochucId getId() {
        return this.id;
    }
    
    public void setId(TochucId id) {
        this.id = id;
    }
    public Diadiem getDiadiem() {
        return this.diadiem;
    }
    
    public void setDiadiem(Diadiem diadiem) {
        this.diadiem = diadiem;
    }
    public Hoinghi getHoinghi() {
        return this.hoinghi;
    }
    
    public void setHoinghi(Hoinghi hoinghi) {
        this.hoinghi = hoinghi;
    }

    public List<Tochuc> excuteQuery(String string) {
                try{
            Session s = NewHibernateUtil.getSessionFactory().openSession();
            s.beginTransaction();
            Query q = s.createQuery(string);
            List<Tochuc> result = q.list();
            s.getTransaction().commit();
            return result;
        }catch(HibernateException e){
            System.out.println(e.getMessage());   
        }
        return null;
    }
    public void Them(){
        Session s = NewHibernateUtil.getSessionFactory().openSession();   
        s.beginTransaction();
        s.persist(this);
        s.getTransaction().commit();
        s.close();
    }

}


